name: Check Commits Ahead of Master

on:
  push:
    branches:
      - main

jobs:
  check-commits-ahead:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Fetch latest changes
      run: git fetch
      
    - name: get epository name
      run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Check for commits ahead of master
      id: git-log
      run: |
        git log --pretty=oneline origin/main..HEAD |wc | awk '{print $GITHUB_ENV "commits ahead of master: " $1}'
        

  
   #   if: steps.git-log.outputs.ahead == ''

  #  - name: Notify via Slack
  #    uses: rtCamp/action-slack-notify@v2.1
  #    if: steps.git-log.outputs.ahead != ''
  #    with:
  #      status: ${{ job.status }}
  #      text: "Commits ahead of master branch: \n```\n$(cat ahead_commits.txt)\n```"
  #      channel_id: ${{ secrets.SLACK_CHANNEL }}
  #      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
