name: Check Commits Ahead of Master

on:
  push:
    branches:
      - main

jobs:
  check-commits-ahead:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Fetch latest changes
      run: git fetch

    - name: Check for commits ahead of master
      id: git-log
      run: |
        git log --pretty=oneline origin/main..HEAD > ahead_commits.txt
        echo "::set-output name=ahead::$(cat ahead_commits.txt)"

    - name: Display results
      if: steps.git-log.outputs.ahead != ''
      run: |
        echo "Commits ahead of master branch:"
        cat ahead_commits.txt
      if: steps.git-log.outputs.ahead == ''

    - name: Notify via Slack
      uses: rtCamp/action-slack-notify@v2.1
      if: steps.git-log.outputs.ahead != ''
      with:
        status: ${{ job.status }}
        text: "Commits ahead of master branch: \n```\n$(cat ahead_commits.txt)\n```"
        channel_id: ${{ secrets.SLACK_CHANNEL }}
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
