name: Track Rollback

on: 
  push:
    branches:
      - main

env:
  PREVIOUS_COMMIT: ${{ steps.previous_commit.outputs.hash }}
  
jobs:
  Rollback:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Get previous commit hash
      id: previous_commit
      run: echo "::set-output name=hash::$(git rev-parse HEAD^)"

    - name: Compare commit hashes
      run: |
        if [ "$PREVIOUS_COMMIT" != "$GITHUB_SHA" ]; then
          echo "Rollback detected! Previous commit: $PREVIOUS_COMMIT"
        else
          echo "No rollback detected."
        fi
